¿Qué diferencia hay entre una Serie y un DataFrame?



In [2]:
# La Serie solo tiene una dimensión, mientras que el Dataframe puede tener más de una dimensión.

Crea dos listas:

- Una que se llame "valores" que tenga 7 números aleatorios.
- Otra que se llame "indices" que tenga 7 strings que se llamen como los días de la semana.

In [3]:
import pandas as pd
import numpy as np

In [4]:
valores= np.random.randint(0,100, (7))
valores

array([27, 18, 31,  9, 69, 54, 20])

In [5]:
indices=['Lun','Mar','Mi','Ju','Vi','Sa','Dom']
indices

['Lun', 'Mar', 'Mi', 'Ju', 'Vi', 'Sa', 'Dom']

A partir de estas dos listas cread una Serie donde la variable "valores" sean los valores de la Serie y la variable indices sean los índices de la Serie.


In [6]:

serie=pd.Series(valores, indices)

A partir de las dos listas anteriores cread un diccionario usando un bucle for. Para hacer esto tenemos el método zip que nos permite iterar por dos listas a la vez. Más informción sobre este método aquí.



In [7]:
dict_serie = {}  #Definimos un diccionario vacío para poder añadir valores y key.
for k, v in zip(indices, valores): 
    dict_serie[k] = v #Para cada key y value en el bucle for asignamos un valor a cada uno a partir del zip de las dos listas.
print(dict_serie)


{'Lun': 27, 'Mar': 18, 'Mi': 31, 'Ju': 9, 'Vi': 69, 'Sa': 54, 'Dom': 20}


In [8]:
#Crea una Serie con el diccionario creado en el punto anterior.
serie_dict= pd.Series(dict_serie)
serie_dict

Lun    27
Mar    18
Mi     31
Ju      9
Vi     69
Sa     54
Dom    20
dtype: int64

In [9]:
#¿Qué forma tiene esta última Serie?
serie_dict.shape

    #Tiene 7 filas

(7,)

In [10]:
#¿Qué tipo de datos tiene?
serie_dict.dtypes


dtype('int64')

In [11]:
#¿Qué tamaño tiene?
serie_dict.size

#Tiene 7 elementos


7

In [12]:
#¿Cuáles son los índices de la Serie?

serie_dict.index

#Indices: dias de la semana

Index(['Lun', 'Mar', 'Mi', 'Ju', 'Vi', 'Sa', 'Dom'], dtype='object')

In [13]:
#¿Y los values?

serie_dict.values

#Los valores son los numeros aleatorios

array([27, 18, 31,  9, 69, 54, 20])

In [14]:
#Extraed el valor para el índice "lunes"

serie_dict['Lun']


27

In [15]:
#Extraed el valor para el índice "lunes", "martes" y "miércoles".

uno=serie_dict['Lun']
dos=serie_dict['Mar']
tres=serie_dict['Mi']

index=uno, dos ,tres
print(index)


(27, 18, 31)


In [16]:
serie_dict['Lun':'Mi']

Lun    27
Mar    18
Mi     31
dtype: int64

In [17]:
#Extraed el valor para el índice "lunes" y "domingo".

uno=serie_dict['Lun']
siete=serie_dict['Dom']

index=uno, siete
print(index)


(27, 20)


In [18]:
serie_dict.loc[['Lun','Dom']]

Lun    27
Dom    20
dtype: int64

Es el turno de los DataFrames

In [19]:
#Cread un array de dos dimensiones con 4 filas y 3 columnas.
array= np.random.randint(0,100,(4,3))
array

array([[33, 35, 59],
       [73, 23, 21],
       [53, 39, 56],
       [11, 61, 54]])

In [20]:
#- Convertid el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".

df=pd.DataFrame(array, columns=['España','Francia','Italia'])
df


España  Francia  Italia
0      33       35      59
1      73       23      21
2      53       39      56
3      11       61      54

In [21]:
# Descargad el archivo "medallas" y cargad el DataFrame con la siguiente línea de código:
df_medallas = pd.read_csv("/Users/veronicabellidosanmartin/Desktop/DATA/ejercicios-adalab/MODULO2/Adalab-DA-promo-b-modulo-2-sprint-1-Ariana-Vero/Pandas/medallas.csv", index_col=["País"])
df_medallas

Unnamed: 0   Oro  Plata  Bronce
País                                            
China                     1  1473    994     720
Japón                     2  1032   1037     985
Corea del Sur             3   745    663     827
Irán                      4   179    181     197
Kazajistán                5   155    158     224
India                     6   154    202     315
Tailandia                 7   132    175     278
Indonesia                 8   112    131     240
China Taipéi              9    99    144     276
Corea del Norte          10    91    120     235

📌 NOTA Para evitar problemas guardar el archivo medallas.csv a la misma altura (en la misma carpeta) que el jupyter donde estamos trabajando.


In [22]:
#- Usando el loc extraed todas las columnas de la fila.

df_medallas.loc[:'China']



Unnamed: 0   Oro  Plata  Bronce
País                                  
China           1  1473    994     720

In [23]:
# Usando el loc extraed todas las columnas de China e Irán.

df_medallas.loc[['China','Irán']]


Unnamed: 0   Oro  Plata  Bronce
País                                  
China           1  1473    994     720
Irán            4   179    181     197

In [24]:
# Usando el loc extraed solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.

df_medallas.loc[['China','Irán']][['Oro','Plata','Bronce']] #La segunda lista accede a las columnas, la primera a los índices


Oro  Plata  Bronce
País                      
China  1473    994     720
Irán    179    181     197

In [25]:
# Usando el iloc extraed la información de la India. Devolved todas las columnas.

df_medallas.iloc[5]


Unnamed: 0      6
Oro           154
Plata         202
Bronce        315
Name: India, dtype: int64

In [26]:
# #Usando el iloc extraed todas las columnas de los paises que estén en posición impar. La primera que nos tendría que salir es Japón y la última Corea del Norte.

df_medallas.iloc[0::2] # utilizamos start en la posición humana 1, hasta el final, saltando de dos en dos para acceder a los impares.


Unnamed: 0   Oro  Plata  Bronce
País                                          
China                   1  1473    994     720
Corea del Sur           3   745    663     827
Kazajistán              5   155    158     224
Tailandia               7   132    175     278
China Taipéi            9    99    144     276

In [27]:
# Utilizando el código del ejercicio anterior, seleccionad unicamente las columnas "Oro", "Plata" y "Bronce".

df_medallas.iloc[0::2][['Oro','Plata','Bronce']]

Oro  Plata  Bronce
País                              
China          1473    994     720
Corea del Sur   745    663     827
Kazajistán      155    158     224
Tailandia       132    175     278
China Taipéi     99    144     276

Contestad a las siguientes preguntas:

In [28]:
# ¿Qué país consiguió más de 200 medallas de oro?

df_medallas.loc[(df_medallas.Oro > 200),['Oro']]

Oro
País               
China          1473
Japón          1032
Corea del Sur   745

In [29]:
# ¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?

df_medallas.loc[(df_medallas.Oro > 200) & (df_medallas.Plata > 1000),['Oro','Plata']]


Oro  Plata
País              
Japón  1032   1037

In [30]:
# ¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?

df_medallas.loc[(df_medallas.Oro > 200) | (df_medallas.Bronce > 700),['Oro','Bronce']]


Oro  Bronce
País                       
China          1473     720
Japón          1032     985
Corea del Sur   745     827

In [32]:
# Como vemos hay una columna que se llama Unnamed: 0 que no nos interesa. Eliminad esa columna

df_medallas=df_medallas.drop(['Unnamed: 0'], axis=1)
df_medallas


Oro  Plata  Bronce
País                                
China            1473    994     720
Japón            1032   1037     985
Corea del Sur     745    663     827
Irán              179    181     197
Kazajistán        155    158     224
India             154    202     315
Tailandia         132    175     278
Indonesia         112    131     240
China Taipéi       99    144     276
Corea del Norte    91    120     235

In [36]:
# Cread una nueva columma que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.

df_medallas['Total']= (df_medallas['Oro']+ df_medallas['Plata']+ df_medallas['Bronce'])
df_medallas


Oro  Plata  Bronce  Total
País                                       
China            1473    994     720   3187
Japón            1032   1037     985   3054
Corea del Sur     745    663     827   2235
Irán              179    181     197    557
Kazajistán        155    158     224    537
India             154    202     315    671
Tailandia         132    175     278    585
Indonesia         112    131     240    483
China Taipéi       99    144     276    519
Corea del Norte    91    120     235    446