¿Qué diferencia hay entre una Serie y un DataFrame?



In [1]:
# La Serie solo tiene una dimensión, mientras que el Dataframe puede tener más de una dimensión.

Crea dos listas:

- Una que se llame "valores" que tenga 7 números aleatorios.
- Otra que se llame "indices" que tenga 7 strings que se llamen como los días de la semana.

In [2]:
import numpy as np
import pandas as pd

In [3]:
valores= np.random.randint(0,100, (7))
valores

array([49, 97,  7, 74, 21, 12, 97])

In [4]:
indices=['Lun','Mar','Mi','Ju','Vi','Sa','Dom']
indices

['Lun', 'Mar', 'Mi', 'Ju', 'Vi', 'Sa', 'Dom']

A partir de estas dos listas cread una Serie donde la variable "valores" sean los valores de la Serie y la variable indices sean los índices de la Serie.


In [5]:
serie=pd.Series(valores, indices)

A partir de las dos listas anteriores cread un diccionario usando un bucle for. Para hacer esto tenemos el método zip que nos permite iterar por dos listas a la vez. Más informción sobre este método aquí.



In [19]:
dict_serie = {}  #Definimos un diccionario vacío para poder añadir valores y key.
for k, v in zip(indices, valores): 
    dict_serie[k] = v #Para cada key y value en el bucle for asignamos un valor a cada uno a partir del zip de las dos listas.
print(dict_serie)


{'Lun': 49, 'Mar': 97, 'Mi': 7, 'Ju': 74, 'Vi': 21, 'Sa': 12, 'Dom': 97}


In [20]:
#Crea una Serie con el diccionario creado en el punto anterior.
serie_dict= pd.Series(dict_serie)
serie_dict

Lun    49
Mar    97
Mi      7
Ju     74
Vi     21
Sa     12
Dom    97
dtype: int64

In [21]:
#¿Qué forma tiene esta última Serie?
serie_dict.shape

    #Tiene 7 filas

(7,)

In [22]:
#¿Qué tipo de datos tiene?
serie_dict.dtypes


dtype('int64')

In [24]:
#¿Qué tamaño tiene?
serie_dict.size

#Tiene 7 elementos


7

In [25]:
#¿Cuáles son los índices de la Serie?

serie_dict.index

#Indices: dias de la semana

Index(['Lun', 'Mar', 'Mi', 'Ju', 'Vi', 'Sa', 'Dom'], dtype='object')

In [26]:
#¿Y los values?

serie_dict.values

#Los valores son los numeros aleatorios

array([49, 97,  7, 74, 21, 12, 97])

In [27]:
#Extraed el valor para el índice "lunes"

serie_dict['Lun']


49

In [33]:
#Extraed el valor para el índice "lunes", "martes" y "miércoles".

uno=serie_dict['Lun']
dos=serie_dict['Mar']
tres=serie_dict['Mi']

index=uno, dos ,tres
print(index)


(49, 97, 7)


In [34]:
serie_dict['Lun':'Mi']

Lun    49
Mar    97
Mi      7
dtype: int64

In [43]:
#Extraed el valor para el índice "lunes" y "domingo".

uno=serie_dict['Lun']
siete=serie_dict['Dom']

index=uno, siete
print(index)


(49, 97)


Es el turno de los DataFrames

In [44]:
#Cread un array de dos dimensiones con 4 filas y 3 columnas.
array= np.random.randint(0,100,(4,3))
array

array([[33, 30, 78],
       [ 6, 81, 26],
       [53, 21, 66],
       [ 4, 94, 25]])

In [46]:
#- Convertid el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".

df=pd.DataFrame(array, columns=['España','Francia','Italia'])
df


España  Francia  Italia
0      33       30      78
1       6       81      26
2      53       21      66
3       4       94      25

In [48]:
# Descargad el archivo "medallas" y cargad el DataFrame con la siguiente línea de código:
df_medallas = pd.read_csv("/Users/veronicabellidosanmartin/Desktop/DATA/ejercicios-adalab/MODULO2/Adalab-DA-promo-b-modulo-2-sprint-1-Ariana-Vero/Pandas/medallas.csv", index_col=["País"])
df_medallas

Unnamed: 0   Oro  Plata  Bronce
País                                            
China                     1  1473    994     720
Japón                     2  1032   1037     985
Corea del Sur             3   745    663     827
Irán                      4   179    181     197
Kazajistán                5   155    158     224
India                     6   154    202     315
Tailandia                 7   132    175     278
Indonesia                 8   112    131     240
China Taipéi              9    99    144     276
Corea del Norte          10    91    120     235

📌 NOTA Para evitar problemas guardar el archivo medallas.csv a la misma altura (en la misma carpeta) que el jupyter donde estamos trabajando.


In [57]:
#- Usando el loc extraed todas las columnas de la fila.

df_medallas.loc[:'China']



Unnamed: 0   Oro  Plata  Bronce
País                                  
China           1  1473    994     720

In [64]:
# Usando el loc extraed todas las columnas de China e Irán.

df_medallas.loc['China'] & df_medallas.loc['Irán']

# Usando el loc extraed solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.
# Usando el iloc extraed la información de la India. Devolved todas las columnas.
# #Usando el iloc extraed todas las columnas de los paises que estén en posición impar. La primera que nos tendría que salir es Japón y la última Corea del Norte.
# Utilizando el código del ejercicio anterior, seleccionad unicamente las columnas "Oro", "Plata" y "Bronce".

Unnamed: 0      0
Oro           129
Plata         160
Bronce        192
dtype: int64

Contestad a las siguientes preguntas:
- ¿Qué país consiguió más de 200 medallas de oro?
- ¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?
- ¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?
  - Como vemos hay una columna que se llama Unnamed: 0 que no nos interesa. Eliminad esa columna.
    - Cread una nueva columma que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.