In [2]:
import numpy as np

In [3]:
#1.¿Cómo podemos crear dos arrays de dos dimensiones usando el método random_sample que tengan los mismos valores?

np.random.seed(42)


In [5]:
arr1, arr2 =np.random.random_sample((3,4)),np.random.random_sample((3,4))
arr1

array([[0.83244264, 0.21233911, 0.18182497, 0.18340451],
       [0.30424224, 0.52475643, 0.43194502, 0.29122914],
       [0.61185289, 0.13949386, 0.29214465, 0.36636184]])

In [8]:
arr2

array([[0.45606998, 0.78517596, 0.19967378, 0.51423444],
       [0.59241457, 0.04645041, 0.60754485, 0.17052412],
       [0.06505159, 0.94888554, 0.96563203, 0.80839735]])

In [9]:
#2.Cread los siguientes arrays:
    #Un array de tres dimensiones con distribución uniforme de 2 x 3 x 5, con números entre 0 y 10, que no tengan decimales y extrae sus valores únicos almacenándolos en una variable.
    
arr3=np.round(np.random.uniform(0,10,(2,3,5)))
arr3_valores=np.unique(arr3)
arr3_valores


array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [10]:
    # Un array de tres dimensiones con distribución binomial de 2 x 3 x 5, con probabilidad de 0.3 y número de pruebas igual a 10. Igual que antes guarda los datos en una variable.

arr4=np.round(np.random.binomial(10,0.3,(2,3,5)))
arr4

array([[[1, 4, 1, 6, 4],
        [2, 0, 4, 4, 4],
        [4, 1, 2, 1, 5]],

       [[3, 2, 1, 2, 2],
        [4, 3, 5, 3, 1],
        [4, 4, 3, 4, 3]]])

In [11]:
arr4_valores=np.unique(arr4)
arr4_valores

array([0, 1, 2, 3, 4, 5, 6])

In [12]:
#3.En esta lección hemos aprendido algunos métodos de teórias de conjuntos. Usando los arrays de elementos únicos obtenidos en el ejercicio anterior realizad las siguientes operaciones:
    #Elementos comunes entre los dos arrays

np.intersect1d(arr3_valores,arr4_valores)
   
# El output de esta celda nos muestra los elementos (como valores únicos) que aparecen tanto en un array como en el otro.

array([0., 1., 2., 3., 4., 5., 6.])

In [13]:
 # Unión de los dos arrays
    # ¿Qué elementos están en el array derivado de la distribución uniforme y no en los únicos de la distribución binomial? Extrae los valores númericos

np.setdiff1d(arr3, arr4_valores)

#⚠️ Explicar cada uno de los outputs que os salgan. Que significa cada una de estas operaciones que hemos ido extrayendo?

# El output de esta celda nos muestra aquellos valores que podemos encontrar en el arr3 pero no podemos encontrar en el arr4_valores, es decir, la diferencia entre ambos.

array([ 7.,  8.,  9., 10.])

In [14]:
#4.Cread dos arrays usando el método random.randint de Numpy con 80 elementos cada uno con números del 1-100, con los siguientes nombres array1 y array2.

array1=np.random.randint(1,100,(80))
array2=np.random.randint(1,100,(80))

In [15]:
array1

array([ 9, 79, 15, 90, 42, 77, 51, 63, 96, 52, 96,  4, 94, 23, 15, 43, 29,
       36, 13, 32, 71, 59, 86, 28, 66, 42, 45, 62, 57,  6, 28, 28, 44, 84,
       30, 62, 75, 92, 89, 62, 97,  1, 27, 62, 77,  3, 70, 72, 27,  9, 62,
       37, 97, 51, 44, 24, 79, 59, 32, 96, 88, 52, 62, 58, 52, 12, 39,  2,
        3, 56, 81, 59,  2,  2, 92, 54, 87, 96, 97,  1])

In [16]:
array2

array([19,  2, 53, 44, 90, 32, 70, 32, 68, 55, 75, 56, 17, 38, 24, 69, 98,
       70, 86, 11, 16, 97, 73, 59, 70, 80, 93,  3, 20, 59, 36, 19, 90, 67,
       19, 20, 96, 71, 52, 33, 40, 39, 82,  1, 11, 92, 57, 89, 50, 23, 31,
       94, 42, 99,  7, 16, 90, 60,  2,  1, 48, 12, 69, 37, 32,  9, 99, 19,
       48, 80,  3, 20, 24, 54, 33, 24, 75, 72, 36, 38])

In [17]:
    # Extraed los valores únicos de cada uno de los arrays y los guardáis en variables en las que se les llame array1 y array2.

array1=np.unique(array1)
array1


array([ 1,  2,  3,  4,  6,  9, 12, 13, 15, 23, 24, 27, 28, 29, 30, 32, 36,
       37, 39, 42, 43, 44, 45, 51, 52, 54, 56, 57, 58, 59, 62, 63, 66, 70,
       71, 72, 75, 77, 79, 81, 84, 86, 87, 88, 89, 90, 92, 94, 96, 97])

In [18]:
array2=np.unique(array2)
array2

array([ 1,  2,  3,  7,  9, 11, 12, 16, 17, 19, 20, 23, 24, 31, 32, 33, 36,
       37, 38, 39, 40, 42, 44, 48, 50, 52, 53, 54, 55, 56, 57, 59, 60, 67,
       68, 69, 70, 71, 72, 73, 75, 80, 82, 86, 89, 90, 92, 93, 94, 96, 97,
       98, 99])

In [19]:
    # Identificad los elementos presentes en el array1 pero no en el array2 y asiganarlo a una variable que se llame array3.

array3=np.setdiff1d(array1,array2)
array3

array([ 4,  6, 13, 15, 27, 28, 29, 30, 43, 45, 51, 58, 62, 63, 66, 77, 79,
       81, 84, 87, 88])

In [20]:
    # Identificad los elementos presentes en el array2 pero no en el array1 y asiganarlo a una variable que se llame array4.

array4=np.setdiff1d(array2,array1)
array4

array([ 7, 11, 16, 17, 19, 20, 31, 33, 38, 40, 48, 50, 53, 55, 60, 67, 68,
       69, 73, 80, 82, 93, 98, 99])

In [21]:
    # Identificad los elementos presentes en ambos arrays y asiganarlos a una variable que se llame array5.

array5=np.setxor1d(array1,array2)
array5

array([ 4,  6,  7, 11, 13, 15, 16, 17, 19, 20, 27, 28, 29, 30, 31, 33, 38,
       40, 43, 45, 48, 50, 51, 53, 55, 58, 60, 62, 63, 66, 67, 68, 69, 73,
       77, 79, 80, 81, 82, 84, 87, 88, 93, 98, 99])

In [22]:
    # ¿Cuál es la relación que existe entre todos estos arrays? 💡 Pista 💡 Tendréis que usar las longitudes de cada uno de los arrays creados.
len_array1=len(array1)
print(len_array1)
len_array2=len(array2)
print((len_array2))
len_array3=len(array3)
print((len_array3))
len_array4=len(array4)
print((len_array4))
len_array5=len(array5)
print((len_array5))

50
53
21
24
45
