In [1]:
import numpy as np

In [6]:
# EJERCICIO 1: Cread tres arrays: de una, dos y tres dimensiones.

# Array de 1 dimensión
array0 = np.random.randint(0, 100, (5))
array0

array([29, 13, 40, 45, 25])

In [2]:
# Array de 2 dimensiones de 2 filas y 3 columnas.

array1 = np.random.randint(0,100, (2,3))
array1

array([[86, 77, 84],
       [68, 31, 97]])

In [3]:
# Array de 3 dimensiones de 2 matrices, 3 filas y 5 columnas.

array2 = np.random.randint(0,100, (2, 3, 5))
array2

array([[[86, 39,  7, 56, 20],
        [40, 23, 25, 29, 22],
        [49, 49, 27, 39, 77]],

       [[46, 47, 64, 88,  4],
        [69, 30, 36, 87, 40],
        [77, 52, 58, 52, 49]]])

In [4]:
# EJERCICIO 2: Chequead las las propiedades básicas de cada array que os hayáis creado. Usad en una función que nos devuelva las propiedades de una array que le pasemos.

# Función para mostrar propiedades

def mostrar_propiedades(array):

    print("las caractéristicas de esta matriz son:","\n")
    print("dimensiones ", array.ndim)
    print("forma ", array.shape)
    print("tamaño ", array.size)
    print("tipo de dato ", array.dtype)

    return



In [5]:
# Propiedades Array0
mostrar_propiedades(array0)

las caractéristicas de esta matriz son: 

dimensiones  2
forma  (2, 3)
tamaño  6
tipo de dato  int32


In [6]:
# Propiedades Array1
mostrar_propiedades(array1)

las caractéristicas de esta matriz son: 

dimensiones  2
forma  (2, 3)
tamaño  6
tipo de dato  int32


In [7]:
# Propiedades Array2
mostrar_propiedades(array2)

las caractéristicas de esta matriz son: 

dimensiones  3
forma  (2, 3, 5)
tamaño  30
tipo de dato  int32


In [16]:
# EJERCICIO 3: Cread una matriz identidad de dos dimensiones de 3 filas y 3 columnas. 

matriz_identidad = np.identity(3)
matriz_identidad



array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
# EJERCICIO 4: Cread una matriz de tres dimensiones de unos igual a la martiz de tres dimensiones creada en el primer ejercicio.

matriz_unos = np.ones_like(array2)
matriz_unos

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [ ]:
# EJERCICIO 5: Es el momento de hacer algunas operaciones entre arrays. 

# ¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicio a la matriz identidad? ¿Por qué?

# No se puede sumar porque no tiene las misma forma.


In [21]:
# En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra. La solución puede ser crear un array nuevo.

array_nuevo = np.random.randint(0,100, (3,3))


In [22]:
matriz_identidad

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
array_nuevo

array([[12, 52, 48],
       [67, 97, 79],
       [26, 76, 24]])

In [24]:
matriz_identidad + array_nuevo

array([[13., 52., 48.],
       [67., 98., 79.],
       [26., 76., 25.]])

In [25]:
# Multiplicad la matriz identidad por la nueva matriz que os creasteis en el ejercicio anterior.

matriz_identidad * array_nuevo

array([[12.,  0.,  0.],
       [ 0., 97.,  0.],
       [ 0.,  0., 24.]])

In [26]:
# Dividid las dos matricess

matriz_identidad / array_nuevo

array([[0.08333333, 0.        , 0.        ],
       [0.        , 0.01030928, 0.        ],
       [0.        , 0.        , 0.04166667]])