In [2]:
import numpy as np
import pandas as pd

EJERICIO 1: Cread un array de dos dimensiones de 5 filas y 3 columnas. Sobre el array creado anteriormente, extraed:

In [3]:
bidimensional = np.random.randint(0, 100, (5, 3))
bidimensional

array([[ 5, 60, 62],
       [26, 78, 22],
       [84, 73, 54],
       [14, 16, 51],
       [41, 74, 82]])

In [4]:
# El valor de la primera fila y la segunda columna.

bidimensional [0,1]

60

In [5]:
#Los valores de la segunda fila y las dos primeras columnas.

bidimensional [1,:2]

array([26, 78])

In [6]:
#Extraed las filas pares (incluyendo la 0) y todas las columnas.

bidimensional[::2,]

array([[ 5, 60, 62],
       [84, 73, 54],
       [41, 74, 82]])

In [7]:
# Extraed los valores que sean mayores que 0.5.

bidimensional[bidimensional > 50]

array([60, 62, 78, 84, 73, 54, 51, 74, 82])

In [8]:
#Extraed los valores menores que 0.2 o mayores que 0.5

bidimensional[(bidimensional < 20) | (bidimensional > 50)]

array([ 5, 60, 62, 78, 84, 73, 54, 14, 16, 51, 74, 82])

EJERCICIO 2: Cread dos array de tres dimensiones:

In [9]:
# Array 1 de 2 matrices, 5 filas y 3 columnas.

array1 = np.random.randint(0, 100, (2, 5, 3))
array1

array([[[41, 70, 38],
        [94, 43, 85],
        [41, 12, 58],
        [22, 22,  0],
        [61, 59, 31]],

       [[77, 35, 20],
        [65, 78, 58],
        [94, 48,  7],
        [30, 25, 51],
        [25,  9, 24]]])

In [10]:
# Array 2 de 3 matrices, 2 filas y 5 columnas. 

array2 = np.random.randint(0, 100, (3, 2, 5))
array2

array([[[48, 51,  6, 93, 71],
        [ 8, 71, 58,  2, 57]],

       [[19, 80, 21, 65,  2],
        [ 6, 64, 72, 24, 62]],

       [[91, 13, 56, 92,  2],
        [61,  5, 47, 84, 93]]])

Haced un análisis exploratorio de los array creados. Recordad que en el ejercicio de ayer nos creamos una función para esto.

In [11]:
def mostrar_propiedades(array):

    print("las caractéristicas de este array son:","\n")
    print("dimensiones ", array.ndim)
    print("forma ", array.shape)
    print("tamaño ", array.size)
    print("tipo de dato ", array.dtype)

    return

In [12]:
# Propiedades array 1
mostrar_propiedades(array1)

las caractéristicas de este array son: 

dimensiones  3
forma  (2, 5, 3)
tamaño  30
tipo de dato  int32


Sumad los dos arrays. ¿Podéis? ¿Por qué?

In [13]:
# Propiedades array 2
mostrar_propiedades(array2)

las caractéristicas de este array son: 

dimensiones  3
forma  (3, 2, 5)
tamaño  30
tipo de dato  int32


In [35]:
array1 + array2  # No se pueden sumar porque no tienen la misma forma.

ValueError: operands could not be broadcast together with shapes (2,5,3) (3,2,5) 

Para cambiar la forma de un array y poder hacer operaciones entre arrays que tienen distintas formas hemos aprendido dos métodos: reshape y transpose. Utiliza estas dos funciones para cambiar la forma de los array y hacer operaciones entre ellos.

In [38]:
# .reshape()
array_reshape = np.reshape(array1, (3,2,5))
array_reshape

array([[[61,  4, 32, 15, 65],
        [52, 18, 80, 52, 30]],

       [[31, 20, 35, 17, 92],
        [56, 63, 36, 43, 70]],

       [[84, 70, 44,  5, 18],
        [21,  8, 53, 80, 53]]])

In [39]:
array2 + array_reshape # Ya se pueden sumar

array([[[ 92,  80, 107,  35,  74],
        [116,  49, 108,  88,  38]],

       [[111,  43, 124,  69, 136],
        [ 71, 152,  78,  97, 162]],

       [[172,  71,  57,  97,  72],
        [ 30,  35, 108, 114, 103]]])

In [36]:
# .transpose()

array_transpose = np.transpose(array1, (2,0,1))
array_transpose

array([[[61, 15, 18, 30, 35],
        [56, 43, 70, 18, 53]],

       [[ 4, 65, 80, 31, 17],
        [63, 70, 44, 21, 80]],

       [[32, 52, 52, 20, 92],
        [36, 84,  5,  8, 53]]])

In [37]:
array2 + array_transpose # Ya se pueden sumar

array([[[ 92,  91,  93,  50,  44],
        [120,  74,  98,  54,  61]],

       [[ 84,  88, 169,  83,  61],
        [ 78, 159,  86,  75, 172]],

       [[120,  53,  65, 112, 146],
        [ 45, 111,  60,  42, 103]]])